### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by chetan-pandit** [project-ecc/Sapphire#102]
Sapphire Auto generated github issue.

STACK TRACE:

Error: connect ECONNREFUSED 127.0.0.1:19119
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)

Node Environment: production

Running Environments: 
Sapphire 1.3.0
Electron 6.0.12
win32 10.0.18362
Locale: en-US

**Comment by Dolaned** [comment]
I am assuming this is Sapphire logging an error from the daemon sayings its not connected @ankhou0 can you get this cleaned up please when you have a chance.

**Comment by Dolaned** [comment]
should be handled now
