### ISSUE TITLE
Got an error when Windows 10 goes to energy saving mode and wakes up again

### ISSUE THREAD

**Issue by ScolliBolli** [project-ecc/Sapphire#107]
Sapphire Auto generated github issue.

STACK TRACE:

Error: getaddrinfo ENOTFOUND medium.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)

Node Environment: production

Running Environments: 
Sapphire 1.3.0
Electron 6.0.12
win32 10.0.18362
Locale: de

**Comment by Dolaned** [comment]
@ankhou0 i dont think its a good idea to log all errors, this is not a big issue but it might seem to be to end users

**Comment by Dolaned** [comment]
fixed https://github.com/project-ecc/sapphire/commit/7a57802bb63e4224c8d2b38b1e3d5bbf8f145915
