### ISSUE TITLE
getaddrinfo ENOTFOUND medium.com

### ISSUE THREAD

**Issue by LukasCH09** [project-ecc/Sapphire#109]
Sapphire Auto generated github issue.

STACK TRACE:

Error: getaddrinfo ENOTFOUND medium.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)

Node Environment: production

Running Environments: 
Sapphire 1.3.0
Electron 6.0.12
win32 10.0.18362
Locale: fr

**Comment by LukasCH09** [comment]
Issue occured while syncing. Computer went into sleep mode, when I awake it, Igot the error.
Sttrange that in above error reort it says "Running Environments win32", as I am running 64 bit OS with 64 bit processor, and also downloaded Sapphire-winx64-1.3.0

However, syncing seems to go on...

**Comment by LukasCH09** [comment]
Seems it is already fixed... #107 

But os identification still seems wrong. Shall I open another issue?

**Comment by Dolaned** [comment]
@LukasCH09 i need a screenshot

**Comment by Dolaned** [comment]
closing as this has been fixe
