### ISSUE TITLE
Mac OS 10.12.6 program end unexpectedly at startup

### ISSUE THREAD

**Issue by jlcargill** [project-ecc/Sapphire#11]
When I first open Sapphire it I never gets past the "Hello, we are getting a few things ready ..." screen. The program quits and gives "Sapphire quit unexpectedly".

Here is the report:
Process:               Sapphire [896]
Path:                  /Applications/Sapphire.app/Contents/MacOS/Sapphire
Identifier:            com.github.csmartinsfct.sapphire
Version:               1.0.0 (1.0.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Sapphire [896]
User ID:               501

Date/Time:             2018-04-20 20:02:33.332 -0500
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        AB594D74-AD33-3900-8183-67A2F68135B0

Time Awake Since Boot: 1900 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Application Specific Information:
Performing @selector(_close:) from sender _NSThemeCloseWidget 0x60000018dea0

**Comment by smaho** [comment]
Fixed in 1.0.1. Please download and retest. https://drive.google.com/drive/folders/1PL9RRzseJnt4v82vEAszB3bCgWE_RanM
