### ISSUE TITLE
first sentence of instructions is not that clear

### ISSUE THREAD

**Issue by eccsupporter** [project-ecc/Sapphire#18]
it says: "If you never installed Lynx or Sapphire on your computer, or if you do not have this folder, please disregard this and simply install Sapphire and run it:"

should it not be something like this:

"If you never installed Lynx or Sapphire on your computer, or if you do not have the folder mentioned below for the operating system you use, please disregard ...

what? this bootstrap or the instruction to delete? 
and simply install Sapphire (is that another file or the same bootstrap?) and run it:

at least not clear to me.

**Comment by csmartinsfct** [comment]
Updated.
