### ISSUE TITLE
what to do after download ecc-bootstrap-20180412.zip?

### ISSUE THREAD

**Issue by eccsupporter** [project-ecc/Sapphire#19]
Finally downloaded the file (took 40 minutes). After downloading the file the instruction says: 
“….and unzip bootstrap.dat into that folder. Then launch Sapphire.”

According to me the bootstrap.dat file is inside the ecc-bootstrap-20180412.zip file and now I understand you have to run the Sapphire v1.0.1.

Maybe the sentence(s) can be more precisely to avoid confusions?

**Comment by csmartinsfct** [comment]
The bootstrap should actually be avoided. We are looking it since some people reported getting stuck in a given block using it. While users who have synced from scratch without it didn't have that issue.

I've updated the guide.
