### ISSUE TITLE
tiles on google drive doesn't show which OS to select?

### ISSUE THREAD

**Issue by eccsupporter** [project-ecc/Sapphire#20]
when I open the google drive containing the instructions and sapphire v1.0.1 it doesn't show exactly which tile to select (not much text visible in tile). Only when you move your mousepointer to the tile you can see which one is what which is less userfriendly.

**Comment by csmartinsfct** [comment]
I'm not sure what you mean in regards to tiles?

https://i.imgur.com/8mJOGML.png

Also this is just for beta testing, once its in production google drive won't be required.

**Comment by eccsupporter** [comment]
tiles are the squares to click on...but google was temp so forget it further
