### ISSUE TITLE
Many more major languages like CJK, German, Spanish, Dutch etc.

### ISSUE THREAD

**Issue by eccsupporter** [project-ecc/Sapphire#22]
What I missed and seriously recommend are the choice in which language you want to install. Especially Asia (!!!!) is not directly English speaking and huge countries e.g. German, Spanish spoken countries a.o. prefer (to say the least) that installation can be in their own language, especially when it comes to assets etc. and to lower the threshold for users. According to me a major point of attention. 

Is this ANS also foreseen for CJK languages or face this difficulties? What is the strategy and should this not be mentioned somewhere?

Of course I want to help get the translations done and hope this was forseen in the current release (and not to be build in for future releases otherwise major issue). Translations can be done realy quickly (within days).

**Comment by csmartinsfct** [comment]
I'll talk to the person responsible for that and get the process started.

I'm not sure if ANS is supported in those languages. @Greg-Griffith

**Comment by eccsupporter** [comment]
I spoke to Lukas and I will check some languages and will try for some others...
