### ISSUE TITLE
text on "Address" main screen

### ISSUE THREAD

**Issue by eccsupporter** [project-ecc/Sapphire#23]
On the main screen after clicking “Contacts” the bottom sentence says: “Type the name of an ANS contact and click to add him or fill the Address input (+ optional Name) to add a regular address.”

I would suggest:
a)	not to mention “male” only, maybe better choose something like “the name”. 
b)	to not make such long sentences so after “… and click to add the name” a dot. 

Next part of the sentence beginning with “…or fill the Address input (+ optional Name) to add a regular address.” is not exactly clear to me what you can do? I can puzzle but would like that it is clear for even the biggest noob to keep the threshold as low as possible.

**Comment by csmartinsfct** [comment]
You actually just gave me an idea how to handle that better! Thanks <3

I struggled to come up with a way to separate "normal addresses" from ans addresses but there isn't a need. I'll push an update when I can.

**Comment by csmartinsfct** [comment]
;)
