### ISSUE TITLE
ANS and Normal Addresses

### ISSUE THREAD

**Issue by eccsupporter** [project-ecc/Sapphire#24]
Under “Your Adresses” is mentiond “All your normal and ANS addresses” with further 2 columns  “ANS addresses” and “Normal Addresses”. Besides the mixed use of capital and small letters what is a “normal address” and should this not be made more clear or maybe better, use another term for “normal address” like “crypto address”, “bitcoin address” or just “address”?

**Comment by csmartinsfct** [comment]
Not quite. The text description under the table name is a paragraph, normal casing applies. On the right side its filters, which follow their own standard across the whole UI.

I could replace the text description with "All your addresses" or something not specific and then for filters use "ans addresses", "addresses" and "all". I'm not sure that would be any less confusing. I suppose it will help once I add tooltips to the UI, where I can further explain things. 

There isn't a need to mention crypto or bitcoin, if they don't know what a normal address is then changing it to any of those would not help.

**Comment by eccsupporter** [comment]
I am fine with all your actions starting from sharing my thoughts...
