### ISSUE TITLE
costs for using addresses etc.

### ISSUE THREAD

**Issue by eccsupporter** [project-ecc/Sapphire#25]
In the Wallet / Addresses there is the message “ANS addresses are recognized by name in the network and have a cost of 10 ecc per month.” 

a) How is this justified and who collects these ecc for what etc? 
b) Should these costs also not be mentioned where you can create contacts? 

For now I think this might become a roadblock for many or do I miss costs from other wallets? Should you then not compare this and see where it is competitive to other rates and fees?

**Comment by csmartinsfct** [comment]
Other wallets don't have ANS. Regular addresses are free. We came up with 10 ecc per month, there is nothing to compare to. Right now it comes out at 1 cent per month. No one collects the ecc, it's just destroyed. You are simply paying to use a service.

There are no costs to creating a contact.

**Comment by eccsupporter** [comment]
Other wallets don't have ANS. Regular addresses are free.
ala: perfect

 We came up with 10 ecc per month, there is nothing to compare to. Right now it comes out at 1 cent per month. 
ala: stress it depends.....

No one collects the ecc, it's just destroyed. You are simply paying to use a service.
ala: do I understand this? you pay ecc but nobody collect these? uuh? why paying, no alternatives? who decides that? probably I don't understand...

There are no costs to creating a contact.
ala: mention it or take care of it...

**Comment by mdtspain** [comment]
By saying that the coins are destroyed I believe that csmartinsfct means that those coins become available for staking. ECC has 25billion coins in roulation and that is also the max coins, so there is no fund for staking rewards unless coins are destroyed. When coins are destroyed, in this case 10, the total coins will be 25 billion -/- 10 coins....making it possible to mine those 10 coins as a staking reward.....you can correct me if I am wrong.

**Comment by AltJ** [comment]
I think that "destroyed" is a bad description of what happens to those coins.  Maybe a better description would be that they are "made available for staking rewards" or "freed for staking rewards"
