### ISSUE TITLE
Transactions filter

### ISSUE THREAD

**Issue by SaluteMB** [project-ecc/Sapphire#27]
I have pending transactions when I choose to show only pending transactions it returns a empty screen and the next button still works but everything is empty. I can only see my transaction when I show All

**Comment by csmartinsfct** [comment]
yep, that will take a while to get fixed. You can keep clicking next until the transactions of the type you want show up.

**Comment by Aklynsmith** [comment]
I am having the same problem . Only my transactions are showing up in the wallet "all pending" yet no balances are displayed in the wallet . Looks like the wallet is empty , but when you check the balances on the blockchain explorer , the balance reflects there.

**Comment by csmartinsfct** [comment]
The pending transactions issue will be fixed in the next update.
