### ISSUE TITLE
Missing Icon

### ISSUE THREAD

**Issue by ghost** [project-ecc/sapphire#41]
Wallet: Sapphire 1.0.1g
OS: Ubuntu 18.04 LTS
DE: Gnome

The icon is present in the application menu, 
but missing in the taskbar and tray bar once the wallet has been opened or minimized.

![image](https://user-images.githubusercontent.com/38443350/39943639-fa4fd84e-5563-11e8-98d6-6113231a8646.png)

**Comment by gl3nda85** [comment]
will look into this, sorry for the late reply

**Comment by ankhou0** [comment]
I am fixing this currently, will notify very shortly with an updated commit.

Will need someone to confirm on a unix build... or I need to create a VM!

**Comment by gl3nda85** [comment]
fixed in https://github.com/project-ecc/sapphire/pull/93
