### ISSUE TITLE
mnemonic seeds

### ISSUE THREAD

**Issue by bluethundr** [project-ecc/Sapphire#44]
When will Sapphire support mnemonic seeds? It's a basic feature that every wallet should have. I don't agree that shipping private keys to the different computers you want to use the ECC wallet on is good practice.  And a mnemonic seed is a lot easier to write down on a piece of paper than a private key is.

**Comment by Greg-Griffith** [comment]
Sapphire is not a wallet and does not contain any logic with regards to the way the wallet functions, it is simply a user interface to display the wallet data in an aesthetically pleasing way. If your request/issue is about the way data being displayed or interacted with, this is the correct repo for the issue. If your request/issue is about protocol functionality or a request for a new feature, please raise an issue in https://github.com/project-ecc/eccoin
