### ISSUE TITLE
Wallet syncing - 0% for past 2 days

### ISSUE THREAD

**Issue by vishycrypto** [project-ecc/Sapphire#45]
Sapphire wallet has been running for 2 days, however there is no progress on syncing. Is there any setting issue? System details:
Windows 8, 64 bit
Sapphire wallet - v1.0.3g & vd
No previous wallet installed
![sapphire issue](https://user-images.githubusercontent.com/40328970/41504374-49886108-71dc-11e8-9546-4c805858de5f.JPG)

**Comment by gl3nda85** [comment]
i dont know if you sorted this out, but its because your daemon isnt installed, as above it says vd it should be v 2.5.11d, this will be fixed in the next sapphire version

**Comment by vishycrypto** [comment]
Hi Dylan,

Till now, I have not been able to sync either Lync or Sapphire.

I have the latest version installed. I chatted with user support several
times but with no use. It's been months now.

Thanks & regards,
Vishal

**Comment by vishycrypto** [comment]
Hi Dylan,

I am on discord. How do I reach you in discord?

Thanks & regards,
Vishal

**Comment by gl3nda85** [comment]
Hey mate my handle on discord is dolaned
