### ISSUE TITLE
Strange behaviour of staking button

### ISSUE THREAD

**Issue by matspb** [project-ecc/sapphire#62]
I mentioned this in Discord and was requested to report here. I have run the Sapphire wallet for several months now. Occasionally it has to be turned off to reboot my PC. When I turn the wallet back on, of course I have to re-enter the password to start staking again. I always have to do this twice! The first time, the white staking button flicks to the right and claims to be staking but then very quickly resets to the left again with staking off. I have to enter the pw a second time. This is always successful and staking begins and remains active.

**Comment by gl3nda85** [comment]
hey mate this will be fixed in the overhaul update, will tag a commit here when done

**Comment by nicholaszuccarelli** [comment]
Yep I have rewritten the staking button and i believe this bug has now been fixed :)

**Comment by gl3nda85** [comment]
this is fixed in the latest dev branch
