### ISSUE TITLE
Sapphire should not immediately start daemon

### ISSUE THREAD

**Issue by smogm** [project-ecc/sapphire#67]
At the moment is seems like sapphire is immediately firing up the daemon if it exists.
After that it runs the update checks and tries to update the daemon.

At least on windows this causes a problem, because the *.exe file of the daemon is in use at that moment and can't be replaced.

One proposed solution:

* start sapphire
* check if daemon exists
  * if exists **->** run daemon --version and compare version with online avaiable version
    * if online == local **->** run daemon
    * if online > local **->** run update and then run daemon
  * if **not** exists **->** run update

**Comment by gl3nda85** [comment]
fixed in https://github.com/project-ecc/sapphire/pull/69
