### ISSUE TITLE
Sapphire icon not displaying in tray 

### ISSUE THREAD

**Issue by Andington** [project-ecc/sapphire#71]
Version: 1.1.2 
OS: Windows 10 Home 64-bit 

While the app is running, the icon in the tray isn't displaying. Also, a right-click window isn't appearing when you click on that icon.  

![Untitled](https://user-images.githubusercontent.com/51105519/58449398-fdbbb180-80d0-11e9-9efe-fe372e1bad45.png)

**Comment by ankhou0** [comment]
I am fixing this currently, will notify very shortly with an updated commit.

**Comment by gl3nda85** [comment]
@ankhou0 you need to build and install to make sure this is fixed

**Comment by gl3nda85** [comment]
fixed in https://github.com/project-ecc/sapphire/pull/93 and https://github.com/project-ecc/sapphire/pull/92
