### ISSUE TITLE
Transactions filter window is transparent 

### ISSUE THREAD

**Issue by Andington** [project-ecc/sapphire#74]
Version: 1.1.2
OS: Windows 10 Home 64-bit

The Transactions filter window is see-thru, and the text on the filter window clashes with the text underneath it. 

![Untitled2](https://user-images.githubusercontent.com/51105519/58453223-e20bd780-80df-11e9-900b-ed91132e1481.png)

**Comment by gl3nda85** [comment]
this has been fixed, check the pre release to confirm :)

**Comment by Pem199** [comment]
I can confirm this issue has been fixed:
![image](https://user-images.githubusercontent.com/15229670/67556454-83409d80-f713-11e9-8240-fddde4f7aaf2.png)
