### ISSUE TITLE
Update failure

### ISSUE THREAD

**Issue by McKing86** [project-ecc/sapphire#77]
Currently running on Windows 10 Sapphire version v1.0.3g & v0.2.5.11d.
Tried to update several times with the settings option and notification option, same attached failure notification as result.
How to solve it and update to current version?

![Update failure](https://user-images.githubusercontent.com/29406487/60090658-3e93fe00-9743-11e9-8ade-471fa10810c6.JPG)

**Comment by Pem199** [comment]
Hey, 
They way daemon build are packaged was changed a while ago.
This caused the current sapphire to be unable to download the latest daemon updates.

So if you want to use the latest daemon, 0.2.5.16, you will have to use lynx 0.2.1 (https://github.com/project-ecc/lynx/releases). Or wait till sapphire 1.1.2 gets through its current testing phase and publically released.

**Comment by McKing86** [comment]
Thanks!
