### ISSUE TITLE
Minimizing sapphire in OSX mojave makes it hide and not come back 

### ISSUE THREAD

**Issue by dmf3030** [project-ecc/sapphire#81]
If you minimize sapphire to the dock when you click on the doc icon the sapphire window doesnt show up.  Top menu bar shows that you have sapphire active and if you toggle fullscreen mode it will bring up fullscreen and then you can go back to windowed mode to make it appear again, so there is a way to recover but its not pretty.

**Comment by gl3nda85** [comment]
i think this is the same issue Mdtbrasil was having ill look into it

**Comment by ankhou0** [comment]
I am fixing this currently, will notify very shortly with an updated commit.

**Comment by arranbalsillie** [comment]
I seem unable to replicate this, could you send a picture @dmf3030 ?

**Comment by dmf3030** [comment]
You know I dont have the same problem on the newest commit, so maybe this was already fixed.  Essentially when you minimized there was no more sapphire window on OSX, no window down in the dock to click on and bring back.  But I think ankou0 fixed it in his commit, would have to dive the commit notes to confirm but since the problem no longer exists I think this is safe to close.
