### ISSUE TITLE
Starting sapphire without a daemon present never starts the freshly downloaded daemon.

### ISSUE THREAD

**Issue by Pem199** [project-ecc/sapphire#82]
When you start sapphire and dont have a daemon in the .eccoin-wallet folder or dont have the .eccoin-wallet folder fails to start the daemon after downloading it.

Looking at the folder while starting sapphire you can see that it downloads the .zip, unpacks it and places the eccoind.exe from the unzipped folder in the .eccoin-wallet folder and even renames it. But then sapphire never starts the daemon. So it just sits there trying to connect to the daemon, eventhough it never started the daemon.

Here is a video of what the console looks like:
https://www.dropbox.com/s/u1xth7y9gh7qwcw/Sapphire%20after%20it%20downloads%20a%20fresh%20daemon.mp4?dl=0

**Comment by Dolaned** [comment]
fixed https://github.com/project-ecc/sapphire/commit/7a57802bb63e4224c8d2b38b1e3d5bbf8f145915
