### ISSUE TITLE
Advanced setting: Redownload daemon fails

### ISSUE THREAD

**Issue by Pem199** [project-ecc/sapphire#83]
There seem to be a few issues with the advanced options that redownloads the daemon.

Firstly it seems to falsely identify that it stopped the daemon.
After clicking redownload daemon option you get one of those toasts saying: Daemon succesfully stopped. Then you get a red toast saying it to remove the daemon, after checking the debug.log file you could clearly see that it wasnt stopped yet when it tried to remove the daemon. 

Then i tried to do it with the daemon already stopped, it removed the daemon but then when it started downloading the new daemon it displayed some other weird behaviour. At first it looked like the progress % was jumping up and down. After futher investigation in the console you could see that every message was being posted 2 times, as if the process was started two times. Which would also explain the progress % jumping up and down, since two processes where reporting their progress to the label.

So 2 problems here:
1. When stopping the daemon it falsely identifies that the daemon was stopped, eventhough it wasnt. 
2. Redownloading the daemon seems to start the process twice.

**Comment by gl3nda85** [comment]
related to 84
