### ISSUE TITLE
Sapphire shows "Blockchain disconnected" when syncing headers

### ISSUE THREAD

**Issue by Pem199** [project-ecc/sapphire#85]
When doing a fresh sync the blockchain connected indicator on the bottom left keeps jumping from green "blockchain connected" to red "blockchain disconnected". This doesnt effect the syncing, nor is the daemon actually stopped (refering to the debugfile), but this would probably look strange to the average user.

Here is a video of what it looks like:
https://www.dropbox.com/s/h0b73ii5qbvigji/Sapphire%20connected-disconnected.mp4?dl=0

**Comment by gl3nda85** [comment]
@HenryYoung42 is this related to your rpc locking up on initial sync?
sapphire checks if it has an active connection to the daemon to determine if the chain is connected to sapphire or not

**Comment by HenryYoung42** [comment]
No because RPC lockup is permament and unrecoverable.

**Comment by gl3nda85** [comment]
im going to close this issue because it is daemon side
