### ISSUE TITLE
when trying to load my sapphire wallet

### ISSUE THREAD

**Issue by Jan2101** [project-ecc/sapphire#88]
when loading sapphire a message keeps displaying to allow or deny sapphire to load.  even if i change security to allow, it does not load on my mac.

**Comment by gl3nda85** [comment]
i need screen shots to help you :)

**Comment by ankhou0** [comment]
Suspect this is to do with unverified developer applications...

**Comment by gl3nda85** [comment]
@ankhou0 that would be partly the problem, but changing it to allow should do the trick

**Comment by Jan2101** [comment]
Please advise what I need to do?  
Regards 

Jan

**Comment by Pem199** [comment]
@Jan2101 Send a screenshot of what you are seeing

**Comment by Jan2101** [comment]
I sent a screenshot.  It just won’t load sapphire and keeps coming up with the deny/allow pop up.  I click allow and it pops up again and so on and so on.  

Thanks. 

Jan

**Comment by Pem199** [comment]
Is the pop-up from windows or perhaps a virusscanner? Do you have a virusscanner?

**Comment by gl3nda85** [comment]
@Jan2101 anymore updates on this.

**Comment by Dolaned** [comment]
closing due to lack of feedback
