### ISSUE TITLE
Staking block on the send is not sensing staking on state on startup

### ISSUE THREAD

**Issue by dmf3030** [project-ecc/sapphire#98]
The send button is greyed out but I dont get the staking block div until I toggle staking off and on, this appears to be a problem with getting the staking status of the daemon on start? though other elements are correctly reporting staking status.

**Comment by gl3nda85** [comment]
will get to this with the hotfix build.

**Comment by Dolaned** [comment]
this is due to people having staking=1 in their conf file after changing to setgenerate, have added a fix

**Comment by Dolaned** [comment]
fixed https://github.com/project-ecc/sapphire/commit/7a57802bb63e4224c8d2b38b1e3d5bbf8f145915
